# Generated by Django 4.1.2 on 2022-10-14 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='cpf',
            field=models.PositiveIntegerField(max_length=11, primary_key=True, serialize=False),
        ),
    ]
